[versions]
android-plugin = "8.10.0"
kotlin-plugin = "2.1.21"

android-desugar = "2.1.5"

androidx-activity = "1.12.0-alpha02"
androidx-appcompat = "1.7.1"
androidx-ktx = "1.16.0"
androidx-lifecycle = "2.9.0"
androidx-navigation3-core = "1.0.0-alpha03"
androidx-splashscreen = "1.0.1"

compose = "1.8.2"
compose-material-icons = "1.7.8"
compose-material3 = "1.4.0-alpha15"

aboutlibraries = "12.1.2"
coil = "3.2.0"
dfc = "1.2"
koin = "4.0.4"
markdown = "0.5.7"
shizuku = "13.1.5"
toptoast = "2.1.0"
zoomable = "2.7.0"

[libraries]
android-desugar = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "android-desugar" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-ktx" }
androidx-lifecycle-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "androidx-navigation3-core" }
androidx-navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "androidx-navigation3-core" }
androidx-splashscreen = { group = "androidx.core", name= "core-splashscreen", version.ref = "androidx-splashscreen" }

compose-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "compose-material-icons" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose-material3" }
compose-material3-window = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "compose-material3" }

aboutlibraries = { group = "com.mikepenz", name = "aboutlibraries-core", version.ref = "aboutlibraries" }
coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
dfc = { group = "com.lazygeniouz", name = "dfc", version.ref = "dfc" }
koin = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }
markdown = { group = "com.github.jeziellago", name = "compose-markdown", version.ref = "markdown" }
shizuku-api = { group = "dev.rikka.shizuku", name = "api", version.ref = "shizuku" }
shizuku-provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "shizuku" }
toptoast = { group = "com.github.aliernfrog", name = "top-toast-compose", version.ref = "toptoast" }
zoomable = { group = "net.engawapg.lib", name = "zoomable", version.ref = "zoomable" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-plugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-plugin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin-plugin" }
aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }