package io.github.aliernfrog.pftool_shared.util

import io.github.aliernfrog.shared.util.SharedString

class PFToolSharedString(override val key: String) : SharedString(key) {
    data object ActionMore : SharedString("action_more")
    data object ActionSelectDeselectAll : SharedString("action_select_deselectAll")
    data object ActionSelectSelectAll : SharedString("action_select_selectAll")
    data object InfoShizukuDisconnected : SharedString("info_shizuku_disconnected")
    data object ListOptions : SharedString("list_options")
    data object ListSorting : SharedString("list_sorting")
    data object ListSortingName : SharedString("list_sorting_name")
    data object ListSortingDate : SharedString("list_sorting_date")
    data object ListSortingSize : SharedString("list_sorting_size")
    data object ListSortingReversed : SharedString("list_sorting_reversed")
    data object ListStyle : SharedString("list_style")
    data object ListStyleList : SharedString("list_style_list")
    data object ListStyleGrid : SharedString("list_style_grid")
    data object ListStyleGridMaxLineSpan : SharedString("list_style_gridMaxLineSpan")
    data object Maps : SharedString("maps")
    data object MapsListReload : SharedString("mapsList_reload")
    data object MapsListStorage : SharedString("mapsList_storage")
    data object MapsListSearch : SharedString("mapsList_search")
    data object MapsListSearchClear : SharedString("mapsList_search_clear")
    data object MapsListSearchNoMatches : SharedString("mapsList_searchNoMatches")
    data object MapsListCount : SharedString("mapsList_count")
    data object MapsListMultiSelection : SharedString("mapsList_multiSelection")
    data object MapsListPickMapFailed : SharedString("mapsList_pickMap_failed")
    data object MapsListSegmentImported : SharedString("mapsList_imported")
    data object MapsListSegmentImportedNoMaps: SharedString("mapsList_imported_noMaps")
    data object MapsListSegmentExported : SharedString("mapsList_exported")
    data object MapsListSegmentExportedNoMaps : SharedString("mapsList_exported_noMaps")
    data object MapsListSegmentShared : SharedString("mapsList_shared")
    data object MapsListSegmentSharedNoMaps : SharedString("mapsList_shared_noMaps")
    data object SettingsLanguage : SharedString("settings_language")
    data object SettingsLanguageSystem : SharedString("settings_language_system")
    data object SettingsLanguageSystemFollow : SharedString("settings_language_system_follow")
    data object SettingsLanguageSystemNotAvailable : SharedString("settings_language_system_notAvailable")
    data object SettingsLanguageOther : SharedString("settings_language_other")
    data object SettingsLanguageProgressBase : SharedString("settings_language_progress_base")
    data object SettingsLanguageProgressPercent : SharedString("settings_language_progress_percent")
    data object SettingsLanguageHelp : SharedString("settings_language_help")
    data object SettingsLanguageHelpDescription : SharedString("settings_language_help_description")
    data object SettingsLanguageHelpDeviceNotAvailable : SharedString("settings_language_help_deviceNotAvailable")
    data object SettingsMaps : SharedString("settings_maps")
    data object SettingsMapsThumbnails : SharedString("settings_maps_thumbnails")
    data object SettingsMapsThumbnailsChosen : SharedString("settings_maps_thumbnails_chosen")
    data object SettingsMapsThumbnailsChosenDescription : SharedString("settings_maps_thumbnails_chosen_description")
    data object SettingsMapsThumbnailsList : SharedString("settings_maps_thumbnails_list")
    data object SettingsMapsThumbnailsListDescription : SharedString("settings_maps_thumbnails_list_description")
    data object SettingsMapsBehavior : SharedString("settings_maps_behavior")
    data object SettingsMapsBehaviorStackup : SharedString("settings_maps_behavior_stackup")
    data object SettingsMapsBehaviorStackupDescription : SharedString("settings_maps_behavior_stackup_description")
    data object SettingsStorage : SharedString("settings_storage")
    data object SettingsStorageStorageAccessType : SharedString("settings_storage_storageAccessType")
    data object SettingsStorageStorageAccessTypeSAF : SharedString("settings_storage_storageAccessType_saf")
    data object SettingsStorageStorageAccessTypeSAFDescription : SharedString("settings_storage_storageAccessType_saf_description")
    data object SettingsStorageStorageAccessTypeShizuku : SharedString("settings_storage_storageAccessType_shizuku")
    data object SettingsStorageStorageAccessTypeShizukuDescription : SharedString("settings_storage_storageAccessType_shizuku_description")
    data object SettingsStorageStorageAccessTypeAllFiles : SharedString("settings_storage_storageAccessType_allFiles")
    data object SettingsStorageStorageAccessTypeAllFilesDescription : SharedString("settings_storage_storageAccessType_allFiles_description")
    data object SettingsStorageFolders : SharedString("settings_storage_folders")
    data object SettingsStorageFoldersChoose : SharedString("settings_storage_folders_choose")
    data object SettingsStorageFoldersRestoreDefault : SharedString("settings_storage_folders_restoreDefault")
    data object SettingsStorageFoldersRecommendedFolder : SharedString("settings_storage_folders_recommendedFolder")
    data object SettingsStorageFoldersNotSet : SharedString("settings_storage_folders_notSet")
    data object SettingsStorageFoldersOpenCurrent : SharedString("settings_storage_folders_openCurrent")
    data object SettingsStorageFoldersOpenRecommended : SharedString("settings_storage_folders_openRecommended")
    data object SettingsStorageFoldersOpenAndroidData : SharedString("settings_storage_folders_openAndroidData")
}